version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test-python3:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: 
          name: Python version
          command: python --version
      - run: 
          name: Install deps
          command: python -m pip install --user -r pip-requirements-test
      - run: 
          name: test
          command: scripts/runners/run_test.sh
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: .coverage
  test-python2:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run: 
          name: Python version
          command: python --version
      - run: 
          name: Install deps
          command: python -m pip install --user -r pip-requirements-test
      - run: 
          name: test
          command: scripts/runners/run_test.sh
workflows:
  version: 2
  test-lint:
    jobs:
      - test-python3
      - test-python2
